name: Build LaTeX CV

on:
  push:
    branches:
      - main  # Runs when you push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex

      - name: Upload PDF to GitHub Pages
        uses: actions/upload-artifact@v3
        with:
          name: cv-pdf
          path: cv.pdf
          
      - name: Commit and Push PDF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add cv.pdf
          git commit -m "Auto-compiled CV"
          git push
