name: Build LaTeX CV

on:
  push:
    branches:
      - main # Runs on every push to main
  pull_request: # Runs on pull requests (optional)
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "*/1 * * * *" # Runs every 1 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex

      - name: Commit and Push PDF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add cv.pdf
          git commit -m "Auto-compiled CV" || echo "No changes to commit"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_branch: gh-pages
          publish_dir: .
          commit_message: "Deploy CV to GitHub Pages"
